---
  name: CI/CD Implementation
  on:
    workflow_dispatch:
    push:
      branches:
        - dev
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: ca-central-1
  permissions:
    id-token: write
    contents: read
###################################################################################  
  jobs:
    Unit-Testing:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4
        - name: Set up Node.js
          uses: actions/setup-node@v4
          with: 
            node-version: "18"
        - name: Install Dependencies
          run: |
            npm install
            npm install --save-dev jest jsdom
        - name: Run Tests
          run: npx jest
          #continue-on-error: true
################################################################################
    Create-ECR-Repo:
      runs-on: ubuntu-latest
      needs: Unit-Testing
      steps:
        - name: Log in to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2
        - name: Check or Create ECR Repository
          id: ecr-check
          run: >
            REPO_NAME="webapp"
            REPO_EXISTS=$(aws ecr describe-repositories --repository-names $REPO_NAME --region $AWS_REGION 2>&1 || true)
            if echo "$REPO_EXISTS" | grep -q "RepositoryNotFoundException"; then
              echo "Repository does not exist. Creating repository $REPO_NAME..."
              aws ecr create-repository --repository-name $REPO_NAME --region $AWS_REGION
            else
              echo "Repository already exists."
              exit 0
            fi      
#################################################################################
    Build_and_Publish:
      runs-on: ubuntu-latest
      needs: Create-ECR-Repo
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4
        - name: Log in to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2
        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Build and Push Docker Image
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: ${{ steps.login-ecr.outputs.registry }}/webapp:1.0.1
  
